package com.demo.fang.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.demo.fang.bean.StockDataBean;

import com.demo.fang.database.StockDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stockDataBeanDaoConfig;

    private final StockDataBeanDao stockDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stockDataBeanDaoConfig = daoConfigMap.get(StockDataBeanDao.class).clone();
        stockDataBeanDaoConfig.initIdentityScope(type);

        stockDataBeanDao = new StockDataBeanDao(stockDataBeanDaoConfig, this);

        registerDao(StockDataBean.class, stockDataBeanDao);
    }
    
    public void clear() {
        stockDataBeanDaoConfig.clearIdentityScope();
    }

    public StockDataBeanDao getStockDataBeanDao() {
        return stockDataBeanDao;
    }

}
